/** ISO 3166-1 alpha-2 country code per destination slug — used for the
 * offline public-holidays calendar (no external API/key needed). */
export const DESTINATION_COUNTRY_CODE: Record<string, string> = {
  argentina: "AR",
  austria: "AT",
  budapest: "HU",
  cambodia: "KH",
  china: "CN",
  copenhagen: "DK",
  croatia: "HR",
  cyprus: "CY",
  dubai: "AE",
  england: "GB",
  france: "FR",
  greece: "GR",
  italy: "IT",
  japan: "JP",
  korea: "KR",
  laos: "LA",
  netherlands: "NL",
  norway: "NO",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  prague: "CZ",
  romania: "RO",
  singapore: "SG",
  spain: "ES",
  sweden: "SE",
  tanzania: "TZ",
  thailand: "TH",
  usa: "US",
  vietnam: "VN",
};
