export type PhraseSeed = { localPhrase: string; translation: string; pronunciation: string; category: string };

/** Curated basic travel phrases per language, keyed by destination slug.
 * translation = Hebrew meaning, pronunciation = Hebrew phonetic transliteration. */
export const PHRASEBOOK_SEEDS: Record<string, PhraseSeed[]> = {
  italy: [
    { localPhrase: "Ciao", translation: "שלום / להתראות", pronunciation: "צ'או", category: "general" },
    { localPhrase: "Grazie", translation: "תודה", pronunciation: "גרציֶה", category: "general" },
    { localPhrase: "Per favore", translation: "בבקשה", pronunciation: "פֶּר פָבוֹרֶה", category: "general" },
    { localPhrase: "Scusi", translation: "סליחה", pronunciation: "סְקוּזִי", category: "general" },
    { localPhrase: "Buongiorno", translation: "בוקר טוב", pronunciation: "בּוֹנְג'וֹרנוֹ", category: "general" },
    { localPhrase: "Buonasera", translation: "ערב טוב", pronunciation: "בּוּאוֹנָסֶרָה", category: "general" },
    { localPhrase: "Quanto costa?", translation: "כמה זה עולה?", pronunciation: "קוּאָנטוֹ קוֹסטָה", category: "shopping" },
    { localPhrase: "Dov'è il bagno?", translation: "איפה השירותים?", pronunciation: "דוֹבֶה איל בָּניוֹ", category: "practical" },
    { localPhrase: "Il conto, per favore", translation: "החשבון, בבקשה", pronunciation: "איל קוֹנטוֹ פֶּר פָבוֹרֶה", category: "food" },
    { localPhrase: "Acqua", translation: "מים", pronunciation: "אָקוּאָה", category: "food" },
    { localPhrase: "Parla inglese?", translation: "אתה מדבר אנגלית?", pronunciation: "פָּרלָה אינגְלֵזֶה", category: "practical" },
    { localPhrase: "Aiuto!", translation: "הצילו!", pronunciation: "אָיוּטוֹ", category: "emergency" },
    { localPhrase: "Sì / No", translation: "כן / לא", pronunciation: "סי / נוֹ", category: "general" },
    { localPhrase: "Delizioso", translation: "טעים מאוד", pronunciation: "דֶלִיציוֹזוֹ", category: "food" },
    { localPhrase: "Salute!", translation: "לחיים!", pronunciation: "סָלוּטֶה", category: "food" },
  ],
  prague: [
    { localPhrase: "Ahoj", translation: "שלום (לא רשמי)", pronunciation: "אָהוֹי", category: "general" },
    { localPhrase: "Děkuji", translation: "תודה", pronunciation: "דְיֶקוּיִי", category: "general" },
    { localPhrase: "Prosím", translation: "בבקשה", pronunciation: "פּרוֹסים", category: "general" },
    { localPhrase: "Promiňte", translation: "סליחה", pronunciation: "פּרוֹמִינְטֶה", category: "general" },
    { localPhrase: "Dobrý den", translation: "יום טוב / שלום (רשמי)", pronunciation: "דוֹבּרִי דֶן", category: "general" },
    { localPhrase: "Kolik to stojí?", translation: "כמה זה עולה?", pronunciation: "קוֹלִיק טוֹ סְטוֹיִי", category: "shopping" },
    { localPhrase: "Kde je toaleta?", translation: "איפה השירותים?", pronunciation: "קְדֶה יֶה טוֹאָלֶטָה", category: "practical" },
    { localPhrase: "Účet, prosím", translation: "החשבון בבקשה", pronunciation: "אוצֶ'ט פּרוֹסים", category: "food" },
    { localPhrase: "Voda", translation: "מים", pronunciation: "וֹוֹדָה", category: "food" },
    { localPhrase: "Mluvíte anglicky?", translation: "אתה מדבר אנגלית?", pronunciation: "מְלוּוִיטֶה אַנְגְלִיצְקִי", category: "practical" },
    { localPhrase: "Pomoc!", translation: "הצילו!", pronunciation: "פּוֹמוֹץ", category: "emergency" },
    { localPhrase: "Ano / Ne", translation: "כן / לא", pronunciation: "אָנוֹ / נֶה", category: "general" },
    { localPhrase: "Na zdraví!", translation: "לחיים!", pronunciation: "נָה זְדְרָבִי", category: "food" },
  ],
  japan: [
    { localPhrase: "こんにちは (Konnichiwa)", translation: "שלום", pronunciation: "קוֹנְנִיצִ'יוָוה", category: "general" },
    { localPhrase: "ありがとう (Arigatou)", translation: "תודה", pronunciation: "אָרִיגָטוֹ", category: "general" },
    { localPhrase: "お願いします (Onegaishimasu)", translation: "בבקשה", pronunciation: "אוֹנֶגָאיְשִימָס", category: "general" },
    { localPhrase: "すみません (Sumimasen)", translation: "סליחה / התנצלות", pronunciation: "סוּמִימָסֶן", category: "general" },
    { localPhrase: "おはようございます (Ohayou gozaimasu)", translation: "בוקר טוב", pronunciation: "אוֹהָיוֹ גוֹזָאִימָס", category: "general" },
    { localPhrase: "いくらですか (Ikura desu ka)", translation: "כמה זה עולה?", pronunciation: "אִיקוּרָה דֶסְקָה", category: "shopping" },
    { localPhrase: "トイレはどこですか (Toire wa doko desu ka)", translation: "איפה השירותים?", pronunciation: "טוֹאִירֶה וָה דוֹקוֹ דֶסְקָה", category: "practical" },
    { localPhrase: "お会計お願いします (Okaikei onegaishimasu)", translation: "החשבון בבקשה", pronunciation: "אוֹקָאיְקֵיי אוֹנֶגָאיְשִימָס", category: "food" },
    { localPhrase: "水 (Mizu)", translation: "מים", pronunciation: "מִיזוּ", category: "food" },
    { localPhrase: "英語を話せますか (Eigo wo hanasemasu ka)", translation: "אתה מדבר אנגלית?", pronunciation: "אֶיְגוֹ וֹוֹ הָנָסֶמָסְקָה", category: "practical" },
    { localPhrase: "助けて! (Tasukete!)", translation: "הצילו!", pronunciation: "טָסוּקֶטֶה", category: "emergency" },
    { localPhrase: "はい / いいえ (Hai / Iie)", translation: "כן / לא", pronunciation: "הַאי / אִיאֶה", category: "general" },
    { localPhrase: "おいしい (Oishii)", translation: "טעים!", pronunciation: "אוֹאִישִי", category: "food" },
    { localPhrase: "乾杯! (Kanpai!)", translation: "לחיים!", pronunciation: "קָנְפָּאי", category: "food" },
  ],
  copenhagen: [
    { localPhrase: "Hej", translation: "שלום", pronunciation: "הַיי", category: "general" },
    { localPhrase: "Tak", translation: "תודה", pronunciation: "טָק", category: "general" },
    { localPhrase: "Undskyld", translation: "סליחה", pronunciation: "אוּנְסְקִיל", category: "general" },
    { localPhrase: "Vær så venlig", translation: "בבקשה", pronunciation: "וֶר סוֹ וֶנְלִי", category: "general" },
    { localPhrase: "Godmorgen", translation: "בוקר טוב", pronunciation: "גוֹד מוֹרְן", category: "general" },
    { localPhrase: "Hvor meget koster det?", translation: "כמה זה עולה?", pronunciation: "וְוֹר מָיֶל קוֹסְטֶר דֶה", category: "shopping" },
    { localPhrase: "Hvor er toilettet?", translation: "איפה השירותים?", pronunciation: "וְוֹר אֶר טוֹאָלֶטֶט", category: "practical" },
    { localPhrase: "Regningen, tak", translation: "החשבון בבקשה", pronunciation: "רַיְנִינְגֶן טָק", category: "food" },
    { localPhrase: "Vand", translation: "מים", pronunciation: "וָאן", category: "food" },
    { localPhrase: "Taler du engelsk?", translation: "אתה מדבר אנגלית?", pronunciation: "טָלֶר דוּ אֶנְגֶלְסְק", category: "practical" },
    { localPhrase: "Hjælp!", translation: "הצילו!", pronunciation: "יֶלְפּ", category: "emergency" },
    { localPhrase: "Ja / Nej", translation: "כן / לא", pronunciation: "יָה / נַיי", category: "general" },
    { localPhrase: "Skål!", translation: "לחיים!", pronunciation: "סְקוֹל", category: "food" },
  ],
  laos: [
    { localPhrase: "Sabaidee", translation: "שלום", pronunciation: "סָבָּאיְדִי", category: "general" },
    { localPhrase: "Khob chai", translation: "תודה", pronunciation: "קוֹפּ צַ'אי", category: "general" },
    { localPhrase: "Khor thod", translation: "סליחה", pronunciation: "קוֹר טוֹד", category: "general" },
    { localPhrase: "Thao dai?", translation: "כמה זה עולה?", pronunciation: "טָאוֹ דַאי", category: "shopping" },
    { localPhrase: "Hong nam yu sai?", translation: "איפה השירותים?", pronunciation: "הוֹנְג נַאם יוּ סַאי", category: "practical" },
    { localPhrase: "Nam", translation: "מים", pronunciation: "נָאם", category: "food" },
    { localPhrase: "Jao vao pha-sa Angkit dai bor?", translation: "אתה מדבר אנגלית?", pronunciation: "צַ'אוֹ וָאוֹ פָאסָא אָנְגְקִיט דַאי בּוֹר", category: "practical" },
    { localPhrase: "Suay!", translation: "לחיים!", pronunciation: "סוּאָי", category: "food" },
  ],
  cambodia: [
    { localPhrase: "Suosdei", translation: "שלום", pronunciation: "סוּאוֹסְדַיי", category: "general" },
    { localPhrase: "Arkun", translation: "תודה", pronunciation: "אָארְקוּן", category: "general" },
    { localPhrase: "Sohm", translation: "בבקשה", pronunciation: "סוֹם", category: "general" },
    { localPhrase: "Sohm toh", translation: "סליחה", pronunciation: "סוֹם טוֹה", category: "general" },
    { localPhrase: "Tlai punman?", translation: "כמה זה עולה?", pronunciation: "טְלַאי פּוּנְמָאן", category: "shopping" },
    { localPhrase: "Bantob teuk nov ae na?", translation: "איפה השירותים?", pronunciation: "בָּאנְטוֹפּ טֶאוּק נוֹוו אֵה נָא", category: "practical" },
    { localPhrase: "Teuk", translation: "מים", pronunciation: "טֶאוּק", category: "food" },
    { localPhrase: "Chol muoy!", translation: "לחיים!", pronunciation: "צ'וֹל מוּאוֹי", category: "food" },
  ],
  sweden: [
    { localPhrase: "Hej", translation: "שלום", pronunciation: "הַיי", category: "general" },
    { localPhrase: "Tack", translation: "תודה", pronunciation: "טָאק", category: "general" },
    { localPhrase: "Snälla", translation: "בבקשה", pronunciation: "סְנֶלָה", category: "general" },
    { localPhrase: "Ursäkta", translation: "סליחה", pronunciation: "אוּרְשֶקְטָה", category: "general" },
    { localPhrase: "Hur mycket kostar det?", translation: "כמה זה עולה?", pronunciation: "הוּר מִיקֶה קוֹסְטָר דֶה", category: "shopping" },
    { localPhrase: "Var är toaletten?", translation: "איפה השירותים?", pronunciation: "וָואר אֶר טוּאָלֶטֶן", category: "practical" },
    { localPhrase: "Notan, tack", translation: "החשבון בבקשה", pronunciation: "נוֹטָן טָאק", category: "food" },
    { localPhrase: "Vatten", translation: "מים", pronunciation: "וָאטֶן", category: "food" },
    { localPhrase: "Pratar du engelska?", translation: "אתה מדבר אנגלית?", pronunciation: "פְּרָאטָר דוּ אֶנְגֶלְסְקָה", category: "practical" },
    { localPhrase: "Skål!", translation: "לחיים!", pronunciation: "סְקוֹל", category: "food" },
  ],
  dubai: [
    { localPhrase: "مرحبا (Marhaba)", translation: "שלום", pronunciation: "מַרְחָבָּא", category: "general" },
    { localPhrase: "شكرا (Shukran)", translation: "תודה", pronunciation: "שֻׁכְּרָן", category: "general" },
    { localPhrase: "من فضلك (Min fadlak)", translation: "בבקשה", pronunciation: "מִן פָדְלַכּ", category: "general" },
    { localPhrase: "آسف (Asif)", translation: "סליחה", pronunciation: "אָסִיף", category: "general" },
    { localPhrase: "بكم هذا؟ (Bikam hatha?)", translation: "כמה זה עולה?", pronunciation: "בִּכַּם הַאדָ'א", category: "shopping" },
    { localPhrase: "أين الحمام؟ (Ayn al-hammam?)", translation: "איפה השירותים?", pronunciation: "אַיְן אלְחַמָּאם", category: "practical" },
    { localPhrase: "ماء (Ma')", translation: "מים", pronunciation: "מַאא", category: "food" },
    { localPhrase: "هل تتكلم انجليزي؟ (Hal tatakalam injlizi?)", translation: "אתה מדבר אנגלית?", pronunciation: "הַל תַתְכַּלַם אִנְגְלִיזִי", category: "practical" },
  ],
  england: [
    { localPhrase: "Hello", translation: "שלום", pronunciation: "הֶלוֹ", category: "general" },
    { localPhrase: "Thank you", translation: "תודה", pronunciation: "תֶ'נְק יוּ", category: "general" },
    { localPhrase: "Please", translation: "בבקשה", pronunciation: "פְּלִיז", category: "general" },
    { localPhrase: "Excuse me / Sorry", translation: "סליחה", pronunciation: "אֶקְסְקְיוּז מִי / סוֹרִי", category: "general" },
    { localPhrase: "How much is this?", translation: "כמה זה עולה?", pronunciation: "הָאוּ מַאץ' איז דִיס", category: "shopping" },
    { localPhrase: "Where's the loo?", translation: "איפה השירותים?", pronunciation: "וֶוארְז דָ לוּ", category: "practical" },
    { localPhrase: "Could I get the bill, please?", translation: "אפשר את החשבון בבקשה?", pronunciation: "קוּד אַיי גֶט דָ בִּיל פְּלִיז", category: "food" },
    { localPhrase: "Cheers!", translation: "לחיים! (גם: תודה)", pronunciation: "צִ'ירְז", category: "food" },
  ],
  netherlands: [
    { localPhrase: "Hallo", translation: "שלום", pronunciation: "הָאלוֹ", category: "general" },
    { localPhrase: "Dank je wel", translation: "תודה", pronunciation: "דָאנְק יֶה וֶול", category: "general" },
    { localPhrase: "Alsjeblieft", translation: "בבקשה", pronunciation: "אָלְסְיֶה בְּלִיפְט", category: "general" },
    { localPhrase: "Sorry / Pardon", translation: "סליחה", pronunciation: "סוֹרִי / פַּרְדוֹן", category: "general" },
    { localPhrase: "Hoeveel kost dit?", translation: "כמה זה עולה?", pronunciation: "הוּפֵיל קוֹסְט דִיט", category: "shopping" },
    { localPhrase: "Waar is het toilet?", translation: "איפה השירותים?", pronunciation: "וָואר איז הֶט טוּאָלֶט", category: "practical" },
    { localPhrase: "De rekening, alsjeblieft", translation: "החשבון בבקשה", pronunciation: "דֶה רֵקֶנִינְג אָלְסְיֶה בְּלִיפְט", category: "food" },
    { localPhrase: "Water", translation: "מים", pronunciation: "וָואטֶר", category: "food" },
    { localPhrase: "Spreekt u Engels?", translation: "אתה מדבר אנגלית?", pronunciation: "סְפְּרֵיקְט אוּ אֶנְגֶלְס", category: "practical" },
    { localPhrase: "Proost!", translation: "לחיים!", pronunciation: "פְּרוֹסְט", category: "food" },
  ],
  tanzania: [
    { localPhrase: "Jambo", translation: "שלום", pronunciation: "גַ'אמְבּוֹ", category: "general" },
    { localPhrase: "Asante", translation: "תודה", pronunciation: "אָסָאנְטֶה", category: "general" },
    { localPhrase: "Tafadhali", translation: "בבקשה", pronunciation: "טָאפָדָ'אלִי", category: "general" },
    { localPhrase: "Samahani", translation: "סליחה", pronunciation: "סָאמָהָאנִי", category: "general" },
    { localPhrase: "Bei gani?", translation: "כמה זה עולה?", pronunciation: "בֵּיי גָאנִי", category: "shopping" },
    { localPhrase: "Choo kiko wapi?", translation: "איפה השירותים?", pronunciation: "צ'וֹאוֹ קִיקוֹ וָאפִּי", category: "practical" },
    { localPhrase: "Maji", translation: "מים", pronunciation: "מָאגִ'י", category: "food" },
    { localPhrase: "Unazungumza Kiingereza?", translation: "אתה מדבר אנגלית?", pronunciation: "אוּנָאזוּנְגוּמְזָה קִיאִינְגֶרֶזָה", category: "practical" },
    { localPhrase: "Karibu!", translation: "ברוך הבא / בבקשה", pronunciation: "קָארִיבּוּ", category: "general" },
  ],
  greece: [
    { localPhrase: "Γεια σου (Yassou)", translation: "שלום", pronunciation: "יָאסוּ", category: "general" },
    { localPhrase: "Ευχαριστώ (Efharisto)", translation: "תודה", pronunciation: "אֶפְחָארִיסְטוֹ", category: "general" },
    { localPhrase: "Παρακαλώ (Parakalo)", translation: "בבקשה", pronunciation: "פָּארָאקָאלוֹ", category: "general" },
    { localPhrase: "Συγγνώμη (Signomi)", translation: "סליחה", pronunciation: "סִיגְנוֹמִי", category: "general" },
    { localPhrase: "Πόσο κάνει; (Poso kani?)", translation: "כמה זה עולה?", pronunciation: "פּוֹסוֹ קָאנִי", category: "shopping" },
    { localPhrase: "Πού είναι η τουαλέτα; (Pou ine i toualeta?)", translation: "איפה השירותים?", pronunciation: "פּוּ אִינֶה אִי טוּאָלֶטָה", category: "practical" },
    { localPhrase: "Νερό (Nero)", translation: "מים", pronunciation: "נֶרוֹ", category: "food" },
    { localPhrase: "Μιλάτε αγγλικά; (Milate agglika?)", translation: "אתה מדבר אנגלית?", pronunciation: "מִילָאטֶה אָנְגְלִיקָה", category: "practical" },
    { localPhrase: "Γεια μας! (Yamas!)", translation: "לחיים!", pronunciation: "יָאמָאס", category: "food" },
  ],
  norway: [
    { localPhrase: "Hei", translation: "שלום", pronunciation: "הַיי", category: "general" },
    { localPhrase: "Takk", translation: "תודה", pronunciation: "טָאק", category: "general" },
    { localPhrase: "Vær så snill", translation: "בבקשה", pronunciation: "וֶר סוֹ סְנִיל", category: "general" },
    { localPhrase: "Unnskyld", translation: "סליחה", pronunciation: "אוּנְשִיל", category: "general" },
    { localPhrase: "Hvor mye koster det?", translation: "כמה זה עולה?", pronunciation: "וְוֹר מִיֶה קוֹסְטֶר דֶה", category: "shopping" },
    { localPhrase: "Hvor er toalettet?", translation: "איפה השירותים?", pronunciation: "וְוֹר אֶר טוּאָלֶטֶה", category: "practical" },
    { localPhrase: "Vann", translation: "מים", pronunciation: "וָאן", category: "food" },
    { localPhrase: "Snakker du engelsk?", translation: "אתה מדבר אנגלית?", pronunciation: "סְנָאקֶר דוּ אֶנְגֶלְסְק", category: "practical" },
    { localPhrase: "Skål!", translation: "לחיים!", pronunciation: "סְקוֹל", category: "food" },
  ],
  china: [
    { localPhrase: "你好 (Nǐ hǎo)", translation: "שלום", pronunciation: "נִי הָאוֹ", category: "general" },
    { localPhrase: "谢谢 (Xièxiè)", translation: "תודה", pronunciation: "שְׁיֶה שְׁיֶה", category: "general" },
    { localPhrase: "请 (Qǐng)", translation: "בבקשה", pronunciation: "צִ'ינְג", category: "general" },
    { localPhrase: "对不起 (Duìbùqǐ)", translation: "סליחה", pronunciation: "דוּאִי בּוּ צִ'י", category: "general" },
    { localPhrase: "多少钱? (Duōshǎo qián?)", translation: "כמה זה עולה?", pronunciation: "דוּאוֹ שָׁאוֹ צְ'יֶן", category: "shopping" },
    { localPhrase: "厕所在哪里? (Cèsuǒ zài nǎlǐ?)", translation: "איפה השירותים?", pronunciation: "צֶ'ה סוּוֹ דְזַאי נָה לִי", category: "practical" },
    { localPhrase: "水 (Shuǐ)", translation: "מים", pronunciation: "שְׁוֵוי", category: "food" },
    { localPhrase: "你会说英语吗? (Nǐ huì shuō yīngyǔ ma?)", translation: "אתה מדבר אנגלית?", pronunciation: "נִי הוּאֵי שוּוֹ יִנְג יוּ מָה", category: "practical" },
    { localPhrase: "干杯! (Gānbēi!)", translation: "לחיים!", pronunciation: "גָּאן בֵּיי", category: "food" },
  ],
  singapore: [
    { localPhrase: "Hello", translation: "שלום", pronunciation: "הֶלוֹ", category: "general" },
    { localPhrase: "Terima kasih", translation: "תודה", pronunciation: "טְרִימָה קָאסִיה", category: "general" },
    { localPhrase: "Tolong", translation: "בבקשה", pronunciation: "טוֹלוֹנְג", category: "general" },
    { localPhrase: "Maaf", translation: "סליחה", pronunciation: "מָאאָף", category: "general" },
    { localPhrase: "Berapa harga?", translation: "כמה זה עולה?", pronunciation: "בְּרָאפָּה הָארְגָה", category: "shopping" },
    { localPhrase: "Where's the toilet?", translation: "איפה השירותים?", pronunciation: "וֶוארְז דָ טוֹיְלֶט", category: "practical" },
    { localPhrase: "Air", translation: "מים", pronunciation: "אָאיִר", category: "food" },
    { localPhrase: "Can I get the bill?", translation: "אפשר את החשבון?", pronunciation: "קֶן אַיי גֶט דָ בִּיל", category: "food" },
  ],
  spain: [
    { localPhrase: "Hola", translation: "שלום", pronunciation: "אוֹלָה", category: "general" },
    { localPhrase: "Gracias", translation: "תודה", pronunciation: "גְרָסְיָאס", category: "general" },
    { localPhrase: "Por favor", translation: "בבקשה", pronunciation: "פּוֹר פָאבוֹר", category: "general" },
    { localPhrase: "Perdón", translation: "סליחה", pronunciation: "פֶּרְדוֹן", category: "general" },
    { localPhrase: "¿Cuánto cuesta?", translation: "כמה זה עולה?", pronunciation: "קוּאָנְטוֹ קוּאֶסְטָה", category: "shopping" },
    { localPhrase: "¿Dónde está el baño?", translation: "איפה השירותים?", pronunciation: "דוֹנְדֶה אֶסְטָה אֶל בָּניוֹ", category: "practical" },
    { localPhrase: "La cuenta, por favor", translation: "החשבון בבקשה", pronunciation: "לָה קוּאֶנְטָה פּוֹר פָאבוֹר", category: "food" },
    { localPhrase: "Agua", translation: "מים", pronunciation: "אָגוּאָה", category: "food" },
    { localPhrase: "¿Hablas inglés?", translation: "אתה מדבר אנגלית?", pronunciation: "אָבְּלָאס אִינְגְלֶס", category: "practical" },
    { localPhrase: "¡Salud!", translation: "לחיים!", pronunciation: "סָאלוּד", category: "food" },
  ],
  portugal: [
    { localPhrase: "Olá", translation: "שלום", pronunciation: "אוֹלָה", category: "general" },
    { localPhrase: "Obrigado/a", translation: "תודה", pronunciation: "אוֹבְּרִיגָדוּ/ה", category: "general" },
    { localPhrase: "Por favor", translation: "בבקשה", pronunciation: "פּוֹר פָאבוֹר", category: "general" },
    { localPhrase: "Desculpe", translation: "סליחה", pronunciation: "דֶשְׁקוּלְפֶּה", category: "general" },
    { localPhrase: "Quanto custa?", translation: "כמה זה עולה?", pronunciation: "קוּאָנְטוֹ קוּשְׁטָה", category: "shopping" },
    { localPhrase: "Onde é a casa de banho?", translation: "איפה השירותים?", pronunciation: "אוֹנְדֶה אֶה אָה קָאזָה דֶה בָּניוֹ", category: "practical" },
    { localPhrase: "A conta, por favor", translation: "החשבון בבקשה", pronunciation: "אָה קוֹנְטָה פּוֹר פָאבוֹר", category: "food" },
    { localPhrase: "Água", translation: "מים", pronunciation: "אָגוּאָה", category: "food" },
    { localPhrase: "Fala inglês?", translation: "אתה מדבר אנגלית?", pronunciation: "פָאלָה אִינְגְלֶש", category: "practical" },
    { localPhrase: "Saúde!", translation: "לחיים!", pronunciation: "סָאאוּדֶה", category: "food" },
  ],
  france: [
    { localPhrase: "Bonjour", translation: "שלום / בוקר טוב", pronunciation: "בּוֹנְז'וּר", category: "general" },
    { localPhrase: "Merci", translation: "תודה", pronunciation: "מֶרְסִי", category: "general" },
    { localPhrase: "S'il vous plaît", translation: "בבקשה", pronunciation: "סִיל וּ פְּלֶה", category: "general" },
    { localPhrase: "Excusez-moi", translation: "סליחה", pronunciation: "אֶקְסְקִיזֶה מוּאָה", category: "general" },
    { localPhrase: "Combien ça coûte?", translation: "כמה זה עולה?", pronunciation: "קוֹמְבְּיֶן סָה קוּט", category: "shopping" },
    { localPhrase: "Où sont les toilettes?", translation: "איפה השירותים?", pronunciation: "אוּ סוֹן לֶה טוּאָלֶט", category: "practical" },
    { localPhrase: "L'addition, s'il vous plaît", translation: "החשבון בבקשה", pronunciation: "לָאדִיסְיוֹן סִיל וּ פְּלֶה", category: "food" },
    { localPhrase: "Eau", translation: "מים", pronunciation: "אוֹ", category: "food" },
    { localPhrase: "Parlez-vous anglais?", translation: "אתה מדבר אנגלית?", pronunciation: "פָּארְלֶה וּ אָנְגְלֶה", category: "practical" },
    { localPhrase: "Santé!", translation: "לחיים!", pronunciation: "סָאנְטֶה", category: "food" },
  ],
  korea: [
    { localPhrase: "안녕하세요 (Annyeonghaseyo)", translation: "שלום", pronunciation: "אָנְיוֹנְג הָסֵיוֹ", category: "general" },
    { localPhrase: "감사합니다 (Gamsahamnida)", translation: "תודה", pronunciation: "קָאמְסָה הָמְנִידָה", category: "general" },
    { localPhrase: "죄송합니다 (Joesonghamnida)", translation: "סליחה", pronunciation: "צֶ'סוֹנְג הָמְנִידָה", category: "general" },
    { localPhrase: "얼마예요? (Eolmayeyo?)", translation: "כמה זה עולה?", pronunciation: "אוֹלְמָה יֵיוֹ", category: "shopping" },
    { localPhrase: "화장실이 어디예요? (Hwajangsili eodiyeyo?)", translation: "איפה השירותים?", pronunciation: "הְוָואגַ'אנְגְסִילִי אוֹדִי יֵיוֹ", category: "practical" },
    { localPhrase: "물 (Mul)", translation: "מים", pronunciation: "מוּל", category: "food" },
    { localPhrase: "영어 하세요? (Yeongeo haseyo?)", translation: "אתה מדבר אנגלית?", pronunciation: "יוֹנְגוֹ הָסֵיוֹ", category: "practical" },
    { localPhrase: "건배! (Geonbae!)", translation: "לחיים!", pronunciation: "קוֹנְבֶּה", category: "food" },
  ],
  cyprus: [
    { localPhrase: "Γεια σου (Yassou)", translation: "שלום", pronunciation: "יָאסוּ", category: "general" },
    { localPhrase: "Ευχαριστώ (Efharisto)", translation: "תודה", pronunciation: "אֶפְחָארִיסְטוֹ", category: "general" },
    { localPhrase: "Παρακαλώ (Parakalo)", translation: "בבקשה", pronunciation: "פָּארָאקָאלוֹ", category: "general" },
    { localPhrase: "Συγγνώμη (Signomi)", translation: "סליחה", pronunciation: "סִיגְנוֹמִי", category: "general" },
    { localPhrase: "Πόσο κάνει; (Poso kani?)", translation: "כמה זה עולה?", pronunciation: "פּוֹסוֹ קָאנִי", category: "shopping" },
    { localPhrase: "Πού είναι η τουαλέτα; (Pou ine i toualeta?)", translation: "איפה השירותים?", pronunciation: "פּוּ אִינֶה אִי טוּאָלֶטָה", category: "practical" },
    { localPhrase: "Νερό (Nero)", translation: "מים", pronunciation: "נֶרוֹ", category: "food" },
    { localPhrase: "Στην υγειά μας! (Stin ygia mas!)", translation: "לחיים!", pronunciation: "סְטִין אִיגְיָה מָאס", category: "food" },
  ],
  croatia: [
    { localPhrase: "Bok", translation: "שלום", pronunciation: "בּוֹק", category: "general" },
    { localPhrase: "Hvala", translation: "תודה", pronunciation: "הְוָואלָה", category: "general" },
    { localPhrase: "Molim", translation: "בבקשה", pronunciation: "מוֹלִים", category: "general" },
    { localPhrase: "Oprostite", translation: "סליחה", pronunciation: "אוֹפְּרוֹסְטִיטֶה", category: "general" },
    { localPhrase: "Koliko košta?", translation: "כמה זה עולה?", pronunciation: "קוֹלִיקוֹ קוֹשְׁטָה", category: "shopping" },
    { localPhrase: "Gdje je toalet?", translation: "איפה השירותים?", pronunciation: "גְדְיֶה יֶה טוֹאָלֶט", category: "practical" },
    { localPhrase: "Voda", translation: "מים", pronunciation: "וֹוֹדָה", category: "food" },
    { localPhrase: "Govorite li engleski?", translation: "אתה מדבר אנגלית?", pronunciation: "גוֹבוֹרִיטֶה לִי אֶנְגְלֶסְקִי", category: "practical" },
    { localPhrase: "Živjeli!", translation: "לחיים!", pronunciation: "זִ'יבְיֶלִי", category: "food" },
  ],
  romania: [
    { localPhrase: "Bună", translation: "שלום", pronunciation: "בּוּנָה", category: "general" },
    { localPhrase: "Mulțumesc", translation: "תודה", pronunciation: "מוּלְצוּמֶסְק", category: "general" },
    { localPhrase: "Vă rog", translation: "בבקשה", pronunciation: "וָה רוֹג", category: "general" },
    { localPhrase: "Scuzați-mă", translation: "סליחה", pronunciation: "סְקוּזָאצִי מָה", category: "general" },
    { localPhrase: "Cât costă?", translation: "כמה זה עולה?", pronunciation: "קָאט קוֹסְטָה", category: "shopping" },
    { localPhrase: "Unde este toaleta?", translation: "איפה השירותים?", pronunciation: "אוּנְדֶה יֶסְטֶה טוֹאָלֶטָה", category: "practical" },
    { localPhrase: "Apă", translation: "מים", pronunciation: "אָפֶּה", category: "food" },
    { localPhrase: "Vorbiți engleză?", translation: "אתה מדבר אנגלית?", pronunciation: "וֹוֹרְבִּיצִי אֶנְגְלֶזָה", category: "practical" },
    { localPhrase: "Noroc!", translation: "לחיים!", pronunciation: "נוֹרוֹק", category: "food" },
  ],
  argentina: [
    { localPhrase: "Hola", translation: "שלום", pronunciation: "אוֹלָה", category: "general" },
    { localPhrase: "Gracias", translation: "תודה", pronunciation: "גְרָסְיָאס", category: "general" },
    { localPhrase: "Por favor", translation: "בבקשה", pronunciation: "פּוֹר פָאבוֹר", category: "general" },
    { localPhrase: "Perdón", translation: "סליחה", pronunciation: "פֶּרְדוֹן", category: "general" },
    { localPhrase: "¿Cuánto sale?", translation: "כמה זה עולה?", pronunciation: "קוּאָנְטוֹ סָאלֶה", category: "shopping" },
    { localPhrase: "¿Dónde está el baño?", translation: "איפה השירותים?", pronunciation: "דוֹנְדֶה אֶסְטָה אֶל בָּניוֹ", category: "practical" },
    { localPhrase: "La cuenta, por favor", translation: "החשבון בבקשה", pronunciation: "לָה קוּאֶנְטָה פּוֹר פָאבוֹר", category: "food" },
    { localPhrase: "Agua", translation: "מים", pronunciation: "אָגוּאָה", category: "food" },
    { localPhrase: "¿Hablás inglés?", translation: "אתה מדבר אנגלית?", pronunciation: "אָבְּלָאס אִינְגְלֶס", category: "practical" },
    { localPhrase: "¡Salud!", translation: "לחיים!", pronunciation: "סָאלוּד", category: "food" },
  ],
  austria: [
    { localPhrase: "Hallo / Grüß Gott", translation: "שלום", pronunciation: "הָאלוֹ / גְרוּס גוֹט", category: "general" },
    { localPhrase: "Danke", translation: "תודה", pronunciation: "דָאנְקֶה", category: "general" },
    { localPhrase: "Bitte", translation: "בבקשה", pronunciation: "בִּיטֶה", category: "general" },
    { localPhrase: "Entschuldigung", translation: "סליחה", pronunciation: "אֶנְטְשׁוּלְדִיגוּנְג", category: "general" },
    { localPhrase: "Wie viel kostet das?", translation: "כמה זה עולה?", pronunciation: "וִי פִיל קוֹסְטֶט דָאס", category: "shopping" },
    { localPhrase: "Wo ist die Toilette?", translation: "איפה השירותים?", pronunciation: "וֹוֹ אִיסְט דִי טוּאָלֶטֶה", category: "practical" },
    { localPhrase: "Die Rechnung, bitte", translation: "החשבון בבקשה", pronunciation: "דִי רֶכְנוּנְג בִּיטֶה", category: "food" },
    { localPhrase: "Wasser", translation: "מים", pronunciation: "וָואסֶר", category: "food" },
    { localPhrase: "Sprechen Sie Englisch?", translation: "אתה מדבר אנגלית?", pronunciation: "שְׁפְּרֶכֶן זִי אֶנְגְלִיש", category: "practical" },
    { localPhrase: "Prost!", translation: "לחיים!", pronunciation: "פְּרוֹסְט", category: "food" },
  ],
  hungary: [
    { localPhrase: "Szia", translation: "שלום", pronunciation: "סִיָּה", category: "general" },
    { localPhrase: "Köszönöm", translation: "תודה", pronunciation: "קֶסֶנֶם", category: "general" },
    { localPhrase: "Kérem", translation: "בבקשה", pronunciation: "קֶרֶם", category: "general" },
    { localPhrase: "Elnézést", translation: "סליחה", pronunciation: "אֶלְנֶזֶשְׁט", category: "general" },
    { localPhrase: "Mennyibe kerül?", translation: "כמה זה עולה?", pronunciation: "מֶניִבֶּה קֶרוּל", category: "shopping" },
    { localPhrase: "Hol van a mosdó?", translation: "איפה השירותים?", pronunciation: "הוֹל וָאן אָה מוֹשְׁדוֹ", category: "practical" },
    { localPhrase: "A számlát, kérem", translation: "החשבון בבקשה", pronunciation: "אָה סָאמְלָאט קֶרֶם", category: "food" },
    { localPhrase: "Víz", translation: "מים", pronunciation: "וִיז", category: "food" },
    { localPhrase: "Beszél angolul?", translation: "אתה מדבר אנגלית?", pronunciation: "בֶּסֶל אָנְגוֹלוּל", category: "practical" },
    { localPhrase: "Egészségedre!", translation: "לחיים!", pronunciation: "אֶגֶסְשֶׁגֶדְרֶה", category: "food" },
  ],
  philippines: [
    { localPhrase: "Kumusta", translation: "שלום", pronunciation: "קוּמוּסְטָה", category: "general" },
    { localPhrase: "Salamat", translation: "תודה", pronunciation: "סָלָאמָאט", category: "general" },
    { localPhrase: "Pakiusap", translation: "בבקשה", pronunciation: "פָּאקִיאוּסָאפ", category: "general" },
    { localPhrase: "Paumanhin", translation: "סליחה", pronunciation: "פָּאאוּמָאנְהִין", category: "general" },
    { localPhrase: "Magkano ito?", translation: "כמה זה עולה?", pronunciation: "מָאגְקָאנוֹ אִיטוֹ", category: "shopping" },
    { localPhrase: "Nasaan ang banyo?", translation: "איפה השירותים?", pronunciation: "נָאסָאאָן אָנְג בָּאניוֹ", category: "practical" },
    { localPhrase: "Tubig", translation: "מים", pronunciation: "טוּבִּיג", category: "food" },
    { localPhrase: "Marunong ka ba mag-Ingles?", translation: "אתה מדבר אנגלית?", pronunciation: "מָארוּנוֹנְג קָה בָּה מָאג אִינְגְלֶס", category: "practical" },
    { localPhrase: "Tagay!", translation: "לחיים!", pronunciation: "טָאגָאי", category: "food" },
  ],
};

export function getPhrasebookSeedForSlug(slug: string): PhraseSeed[] {
  return PHRASEBOOK_SEEDS[slug] ?? [];
}
