export type QuoteDocParams = {
  quoteNumber: string;
  createdAt: Date;
  plannerName: string; // company name if set, otherwise "עודד המנקד"
  clientName: string;
  destinationName: string;
  tripDays: number;
  basePriceCents: number;
  includesBooking: boolean;
  bookingPriceCents: number;
  currency: string;
  notes: string | null;
};

/**
 * Assembles a polished Hebrew quote + boilerplate service-agreement document
 * from a fixed template. This is NOT generated by a live AI model — no LLM
 * API is configured for this app — but the copy is written to read as a
 * complete, professional quote a planner can send as-is.
 */
export function generateQuoteDocument(p: QuoteDocParams): {
  totalCents: number;
  sections: { heading: string; body: string[] }[];
} {
  const totalCents = p.basePriceCents + (p.includesBooking ? p.bookingPriceCents : 0);
  const money = (cents: number) => `${(cents / 100).toFixed(0)} ${p.currency}`;
  const dateStr = p.createdAt.toLocaleDateString("he-IL", { year: "numeric", month: "long", day: "numeric" });

  const sections: { heading: string; body: string[] }[] = [
    {
      heading: "1. הצדדים",
      body: [
        `הצעת מחיר זו (מס' ${p.quoteNumber}, מיום ${dateStr}) ניתנת על ידי ${p.plannerName} ("נותן השירות") ללקוח/ה ${p.clientName} ("הלקוח").`,
      ],
    },
    {
      heading: "2. תיאור השירות",
      body: [
        `תכנון מסלול טיול מלא ליעד ${p.destinationName} למשך ${p.tripDays} ימים, הכולל בניית מסלול יומי מותאם אישית, המלצות אטרקציות ומסעדות, ומפת ניווט אינטראקטיבית.`,
        p.includesBooking
          ? "בנוסף לתכנון, נותן השירות יבצע עבור הלקוח גם הזמנה בפועל של אטרקציות, ו/או טיסות, ו/או מלונות בהתאם למסלול שסוכם."
          : "השירות כולל תכנון בלבד — הזמנת אטרקציות, טיסות ומלונות בפועל אינה כלולה ותבוצע על ידי הלקוח באופן עצמאי.",
      ],
    },
    {
      heading: "3. פירוט מחיר",
      body: [
        `תכנון מסלול: ${money(p.basePriceCents)}`,
        ...(p.includesBooking ? [`ביצוע הזמנות (אטרקציות/טיסות/מלונות): ${money(p.bookingPriceCents)}`] : []),
        `סה"כ לתשלום: ${money(totalCents)}`,
      ],
    },
    {
      heading: "4. תנאי תשלום",
      body: [
        "50% מהסכום כמקדמה בעת אישור הצעה זו, והיתרה עד 14 ימים לפני מועד תחילת הטיול.",
        "התשלום יבוצע באמצעים שיתואמו מול נותן השירות.",
      ],
    },
    {
      heading: "5. מדיניות ביטול",
      body: [
        "ביטול עד 30 יום לפני תחילת הטיול — החזר מלא של המקדמה בניכוי דמי טיפול.",
        "ביטול בטווח של 30-14 יום — החזר של 50% מהמקדמה.",
        "ביטול פחות מ-14 יום לפני תחילת הטיול — המקדמה אינה ניתנת להחזר.",
      ],
    },
    {
      heading: "6. תוקף ההצעה",
      body: ["הצעה זו בתוקף ל-14 יום ממועד ההנפקה, אלא אם צוין אחרת."],
    },
    ...(p.notes ? [{ heading: "7. הערות נוספות", body: [p.notes] }] : []),
  ];

  return { totalCents, sections };
}
