export type WorldCountry = { code: string; name: string; lat: number; lng: number };

/** ISO 3166-1 alpha-2 code → 🇽🇽 flag emoji, computed from Unicode regional
 * indicator symbols instead of hardcoding ~190 emoji by hand. */
export function flagEmoji(code: string): string {
  return code
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
    .join("");
}

// A broad set of real-world travel destinations — code, Hebrew name, and an
// approximate country centroid/capital for placing a pin on the world map.
export const WORLD_COUNTRIES: WorldCountry[] = [
  { code: "IL", name: "ישראל", lat: 31.5, lng: 34.75 },
  { code: "IT", name: "איטליה", lat: 42.5, lng: 12.5 },
  { code: "JP", name: "יפן", lat: 36.2, lng: 138.3 },
  { code: "CZ", name: "צ׳כיה", lat: 49.8, lng: 15.5 },
  { code: "DK", name: "דנמרק", lat: 56.0, lng: 10.0 },
  { code: "CN", name: "סין", lat: 35.0, lng: 103.0 },
  { code: "HU", name: "הונגריה", lat: 47.2, lng: 19.5 },
  { code: "VN", name: "וייטנאם", lat: 16.0, lng: 108.0 },
  { code: "PL", name: "פולין", lat: 52.0, lng: 19.5 },
  { code: "US", name: "ארצות הברית", lat: 39.8, lng: -98.6 },
  { code: "LA", name: "לאוס", lat: 18.0, lng: 103.8 },
  { code: "KH", name: "קמבודיה", lat: 12.6, lng: 105.0 },
  { code: "SE", name: "שוודיה", lat: 62.0, lng: 15.0 },
  { code: "GB", name: "אנגליה", lat: 54.0, lng: -2.0 },
  { code: "NL", name: "הולנד", lat: 52.3, lng: 5.5 },
  { code: "TZ", name: "טנזניה", lat: -6.4, lng: 34.9 },
  { code: "NO", name: "נורבגיה", lat: 62.0, lng: 10.0 },
  { code: "SG", name: "סינגפור", lat: 1.35, lng: 103.8 },
  { code: "TH", name: "תאילנד", lat: 15.0, lng: 101.0 },
  { code: "FR", name: "צרפת", lat: 46.7, lng: 2.5 },
  { code: "CY", name: "קפריסין", lat: 35.1, lng: 33.4 },
  { code: "HR", name: "קרואטיה", lat: 45.5, lng: 16.5 },
  { code: "RO", name: "רומניה", lat: 45.9, lng: 25.0 },
  { code: "AT", name: "אוסטריה", lat: 47.5, lng: 14.5 },
  { code: "PH", name: "הפיליפינים", lat: 12.9, lng: 121.8 },
  { code: "PT", name: "פורטוגל", lat: 39.5, lng: -8.0 },
  { code: "AE", name: "דובאי", lat: 25.2, lng: 55.3 },
  { code: "GR", name: "יוון", lat: 39.0, lng: 22.0 },
  { code: "ES", name: "ספרד", lat: 40.0, lng: -3.7 },
  { code: "KR", name: "קוריאה", lat: 36.5, lng: 127.8 },
  { code: "AR", name: "ארגנטינה", lat: -38.4, lng: -63.6 },
  { code: "DE", name: "גרמניה", lat: 51.2, lng: 10.4 },
  { code: "CH", name: "שוויץ", lat: 46.8, lng: 8.2 },
  { code: "BE", name: "בלגיה", lat: 50.8, lng: 4.4 },
  { code: "IE", name: "אירלנד", lat: 53.4, lng: -8.0 },
  { code: "FI", name: "פינלנד", lat: 64.0, lng: 26.0 },
  { code: "IS", name: "איסלנד", lat: 64.9, lng: -18.5 },
  { code: "TR", name: "טורקיה", lat: 39.0, lng: 35.2 },
  { code: "EG", name: "מצרים", lat: 26.8, lng: 30.8 },
  { code: "MA", name: "מרוקו", lat: 31.8, lng: -7.1 },
  { code: "ZA", name: "דרום אפריקה", lat: -29.0, lng: 24.0 },
  { code: "KE", name: "קניה", lat: -0.02, lng: 37.9 },
  { code: "IN", name: "הודו", lat: 21.0, lng: 78.0 },
  { code: "ID", name: "אינדונזיה", lat: -2.5, lng: 118.0 },
  { code: "MY", name: "מלזיה", lat: 4.2, lng: 101.9 },
  { code: "MX", name: "מקסיקו", lat: 23.6, lng: -102.5 },
  { code: "BR", name: "ברזיל", lat: -14.2, lng: -51.9 },
  { code: "CA", name: "קנדה", lat: 56.1, lng: -106.3 },
  { code: "AU", name: "אוסטרליה", lat: -25.3, lng: 133.8 },
  { code: "NZ", name: "ניו זילנד", lat: -41.0, lng: 174.9 },
  { code: "PE", name: "פרו", lat: -9.2, lng: -75.0 },
  { code: "CL", name: "צ׳ילה", lat: -35.7, lng: -71.5 },
  { code: "CO", name: "קולומביה", lat: 4.6, lng: -74.3 },
  { code: "CU", name: "קובה", lat: 21.5, lng: -77.8 },
  { code: "GE", name: "גאורגיה", lat: 42.3, lng: 43.4 },
  { code: "AM", name: "ארמניה", lat: 40.1, lng: 45.0 },
  { code: "AZ", name: "אזרבייג'ן", lat: 40.1, lng: 47.6 },
  { code: "RU", name: "רוסיה", lat: 61.5, lng: 105.3 },
  { code: "UA", name: "אוקראינה", lat: 48.4, lng: 31.2 },
  { code: "SI", name: "סלובניה", lat: 46.1, lng: 14.8 },
  { code: "SK", name: "סלובקיה", lat: 48.7, lng: 19.7 },
  { code: "BG", name: "בולגריה", lat: 42.7, lng: 25.5 },
  { code: "RS", name: "סרביה", lat: 44.0, lng: 21.0 },
  { code: "AL", name: "אלבניה", lat: 41.2, lng: 20.2 },
  { code: "ME", name: "מונטנגרו", lat: 42.7, lng: 19.4 },
  { code: "MT", name: "מלטה", lat: 35.9, lng: 14.4 },
  { code: "LU", name: "לוקסמבורג", lat: 49.8, lng: 6.1 },
  { code: "LI", name: "ליכטנשטיין", lat: 47.2, lng: 9.5 },
  { code: "MC", name: "מונקו", lat: 43.7, lng: 7.4 },
  { code: "AD", name: "אנדורה", lat: 42.5, lng: 1.5 },
  { code: "SM", name: "סן מרינו", lat: 43.9, lng: 12.5 },
  { code: "VA", name: "הוותיקן", lat: 41.9, lng: 12.45 },
  { code: "NP", name: "נפאל", lat: 28.4, lng: 84.1 },
  { code: "LK", name: "סרי לנקה", lat: 7.9, lng: 80.8 },
  { code: "MV", name: "האיים המלדיביים", lat: 3.2, lng: 73.2 },
  { code: "MM", name: "מיאנמר", lat: 21.9, lng: 96.0 },
  { code: "BD", name: "בנגלדש", lat: 23.7, lng: 90.4 },
  { code: "PK", name: "פקיסטן", lat: 30.4, lng: 69.3 },
  { code: "JO", name: "ירדן", lat: 31.2, lng: 36.5 },
  { code: "LB", name: "לבנון", lat: 33.9, lng: 35.9 },
  { code: "SA", name: "ערב הסעודית", lat: 23.9, lng: 45.1 },
  { code: "QA", name: "קטאר", lat: 25.3, lng: 51.2 },
  { code: "OM", name: "עומאן", lat: 21.5, lng: 55.9 },
  { code: "IR", name: "איראן", lat: 32.4, lng: 53.7 },
  { code: "NG", name: "ניגריה", lat: 9.1, lng: 8.7 },
  { code: "GH", name: "גאנה", lat: 7.9, lng: -1.0 },
  { code: "ET", name: "אתיופיה", lat: 9.1, lng: 40.5 },
  { code: "MU", name: "מאוריציוס", lat: -20.3, lng: 57.6 },
  { code: "SC", name: "סיישל", lat: -4.7, lng: 55.5 },
  { code: "MG", name: "מדגסקר", lat: -18.8, lng: 47.0 },
  { code: "NA", name: "נמיביה", lat: -22.9, lng: 18.5 },
  { code: "BW", name: "בוצואנה", lat: -22.3, lng: 24.7 },
  { code: "ZM", name: "זמביה", lat: -13.1, lng: 27.8 },
  { code: "ZW", name: "זימבבואה", lat: -19.0, lng: 29.2 },
  { code: "UG", name: "אוגנדה", lat: 1.4, lng: 32.3 },
  { code: "RW", name: "רואנדה", lat: -1.9, lng: 29.9 },
  { code: "TW", name: "טייוואן", lat: 23.7, lng: 121.0 },
  { code: "HK", name: "הונג קונג", lat: 22.3, lng: 114.2 },
  { code: "MO", name: "מקאו", lat: 22.2, lng: 113.5 },
  { code: "MN", name: "מונגוליה", lat: 46.9, lng: 103.8 },
  { code: "KZ", name: "קזחסטן", lat: 48.0, lng: 66.9 },
  { code: "UZ", name: "אוזבקיסטן", lat: 41.4, lng: 64.6 },
  { code: "FO", name: "איי פארו", lat: 62.0, lng: -6.8 },
  { code: "GL", name: "גרינלנד", lat: 71.7, lng: -42.6 },
  { code: "EC", name: "אקוודור", lat: -1.8, lng: -78.2 },
  { code: "BO", name: "בוליביה", lat: -16.3, lng: -63.6 },
  { code: "UY", name: "אורוגוואי", lat: -32.5, lng: -55.8 },
  { code: "PY", name: "פרגוואי", lat: -23.4, lng: -58.4 },
  { code: "PA", name: "פנמה", lat: 8.5, lng: -80.8 },
  { code: "CR", name: "קוסטה ריקה", lat: 9.7, lng: -83.8 },
  { code: "GT", name: "גואטמלה", lat: 15.8, lng: -90.2 },
  { code: "DO", name: "הרפובליקה הדומיניקנית", lat: 18.7, lng: -70.2 },
  { code: "JM", name: "ג׳מייקה", lat: 18.1, lng: -77.3 },
  { code: "BS", name: "איי בהאמה", lat: 25.0, lng: -77.4 },
  { code: "BZ", name: "בליז", lat: 17.2, lng: -88.5 },
];

export function countryLookup(): Map<string, WorldCountry> {
  return new Map(WORLD_COUNTRIES.map((c) => [c.code, c]));
}
