import type { ThemeConfig } from "./types";

/**
 * Starting theme direction per destination — distinct color palette + shape
 * + mood note so every destination reads as its own product, not a reskin.
 * Typography is intentionally NOT part of this: one font (Rubik) is used
 * site-wide (see theme/fonts.ts) for consistency and readability.
 */
export const themePresets: Record<string, ThemeConfig> = {
  italy: {
    palette: {
      primary: "#B5502A",
      secondary: "#5B6E4E",
      accent: "#E8B04B",
      background: "#FBF6EE",
      surface: "#FFFFFF",
      text: "#2B2420",
    },
    shape: "organic",
    mood: "Warm Mediterranean terracotta, olive, sun-bleached piazza stone.",
  },
  prague: {
    palette: {
      primary: "#6E2A3A",
      secondary: "#8A7A4E",
      accent: "#C9A24B",
      background: "#F3EDE4",
      surface: "#FFFFFF",
      text: "#231C1E",
    },
    shape: "sharp",
    mood: "Gothic spires, burgundy and gold, old-world engraved elegance.",
  },
  japan: {
    palette: {
      primary: "#B23A48",
      secondary: "#2E3B4E",
      accent: "#C7A46B",
      background: "#F7F5F0",
      surface: "#FFFFFF",
      text: "#1F1F1F",
    },
    shape: "sharp",
    mood: "Wabi-sabi minimalism, sumi ink, single red accent like a hanko stamp.",
  },
  copenhagen: {
    palette: {
      primary: "#3E5C76",
      secondary: "#C9A66B",
      accent: "#D97757",
      background: "#F5F1EA",
      surface: "#FFFFFF",
      text: "#25272B",
    },
    shape: "rounded",
    mood: "Hygge Scandinavian calm, dusty blue and warm wood tones.",
  },
  budapest: {
    palette: {
      primary: "#1E5B5A",
      secondary: "#9C6B30",
      accent: "#D4AF37",
      background: "#F6F0E4",
      surface: "#FFFFFF",
      text: "#20241F",
    },
    shape: "organic",
    mood: "Art nouveau thermal-bath elegance, teal and gold ornament.",
  },
  thailand: {
    palette: {
      primary: "#0E7C7B",
      secondary: "#F2542D",
      accent: "#FFC857",
      background: "#FBF8F1",
      surface: "#FFFFFF",
      text: "#1D2D2C",
    },
    shape: "rounded",
    mood: "Tropical, saturated turquoise and coral, temple gold accents.",
  },
  china: {
    palette: {
      primary: "#A0212B",
      secondary: "#1B1B1B",
      accent: "#D4AF37",
      background: "#F7F1E8",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Imperial red and gold, bold lacquer-and-ink graphic confidence.",
  },
  vietnam: {
    palette: {
      primary: "#1F7A4D",
      secondary: "#D9A441",
      accent: "#C1443C",
      background: "#F5F3E8",
      surface: "#FFFFFF",
      text: "#1E2420",
    },
    shape: "organic",
    mood: "Lush emerald rice terraces, saffron lantern light, riverside calm.",
  },
  poland: {
    palette: {
      primary: "#8C1F28",
      secondary: "#33383D",
      accent: "#C9A24B",
      background: "#F4EFE6",
      surface: "#FFFFFF",
      text: "#1F1E1D",
    },
    shape: "sharp",
    mood: "Amber and brick-red heritage, medieval square warmth.",
  },
  usa: {
    palette: {
      primary: "#1B3A6B",
      secondary: "#B5303B",
      accent: "#E8B93D",
      background: "#F6F3EC",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Americana road-trip diner signage, navy and highway red.",
  },
  laos: {
    palette: {
      primary: "#B5222E",
      secondary: "#2E6E5C",
      accent: "#D4AF37",
      background: "#F6F1E6",
      surface: "#FFFFFF",
      text: "#231E19",
    },
    shape: "organic",
    mood: "Mekong mist, saffron monk robes, quiet temple gold.",
  },
  cambodia: {
    palette: {
      primary: "#1F5C4E",
      secondary: "#B23A2A",
      accent: "#D4AF37",
      background: "#F5F0E2",
      surface: "#FFFFFF",
      text: "#201C16",
    },
    shape: "organic",
    mood: "Sandstone temple carvings, jungle green, weathered Angkor gold.",
  },
  sweden: {
    palette: {
      primary: "#1E4B8C",
      secondary: "#D9A441",
      accent: "#C1443C",
      background: "#F4F5F7",
      surface: "#FFFFFF",
      text: "#1A1E24",
    },
    shape: "rounded",
    mood: "Nordic blue and Falu-red cottages, clean minimal light.",
  },
  dubai: {
    palette: {
      primary: "#B08A3E",
      secondary: "#1B2A41",
      accent: "#E4C27A",
      background: "#F7F3E9",
      surface: "#FFFFFF",
      text: "#201C14",
    },
    shape: "sharp",
    mood: "Desert gold skyline, deep navy night, futuristic luxury.",
  },
  england: {
    palette: {
      primary: "#1F3A5F",
      secondary: "#8C1F2C",
      accent: "#C9A24B",
      background: "#F3F1EC",
      surface: "#FFFFFF",
      text: "#1B1B1B",
    },
    shape: "sharp",
    mood: "Rainy London brick, red telephone box, old-world crest gold.",
  },
  netherlands: {
    palette: {
      primary: "#D9541F",
      secondary: "#1E4B8C",
      accent: "#F2C744",
      background: "#F5F3EC",
      surface: "#FFFFFF",
      text: "#1E1D1A",
    },
    shape: "rounded",
    mood: "Tulip orange and canal-house blue, tidy graphic clarity.",
  },
  tanzania: {
    palette: {
      primary: "#B5651D",
      secondary: "#2E6E5C",
      accent: "#E8B93D",
      background: "#F6F0E2",
      surface: "#FFFFFF",
      text: "#231C15",
    },
    shape: "organic",
    mood: "Savanna dust and acacia gold, Zanzibar turquoise coastline.",
  },
  greece: {
    palette: {
      primary: "#1B5DA8",
      secondary: "#2E3B4E",
      accent: "#E8B93D",
      background: "#F5F5F2",
      surface: "#FFFFFF",
      text: "#1A1E22",
    },
    shape: "rounded",
    mood: "Whitewashed Cycladic walls, Aegean blue, sun-bleached stone.",
  },
  norway: {
    palette: {
      primary: "#1E3A5F",
      secondary: "#4E7A9C",
      accent: "#D97757",
      background: "#F2F3F5",
      surface: "#FFFFFF",
      text: "#1A1E24",
    },
    shape: "sharp",
    mood: "Fjord slate blue, aurora-green accent, crisp Nordic minimalism.",
  },
  singapore: {
    palette: {
      primary: "#B5202A",
      secondary: "#1E5C4A",
      accent: "#D4AF37",
      background: "#F5F3EC",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Garden-city green and Marina Bay skyline red, modern sheen.",
  },
  spain: {
    palette: {
      primary: "#C8102E",
      secondary: "#E8B93D",
      accent: "#2E5C8A",
      background: "#FAF4E8",
      surface: "#FFFFFF",
      text: "#221C15",
    },
    shape: "organic",
    mood: "Flamenco red and gold, sun-drenched plaza warmth.",
  },
  portugal: {
    palette: {
      primary: "#1B6E8C",
      secondary: "#C8422E",
      accent: "#E8B93D",
      background: "#F3F4F2",
      surface: "#FFFFFF",
      text: "#1B1E1D",
    },
    shape: "rounded",
    mood: "Azulejo tile blue, terracotta rooftops, coastal light.",
  },
  france: {
    palette: {
      primary: "#1E3A6B",
      secondary: "#8C1F2C",
      accent: "#C9A24B",
      background: "#F5F3EE",
      surface: "#FFFFFF",
      text: "#1D1B18",
    },
    shape: "sharp",
    mood: "Parisian navy and bordeaux, gilded café elegance.",
  },
  korea: {
    palette: {
      primary: "#1E4FA0",
      secondary: "#C8302E",
      accent: "#2B2B2B",
      background: "#F5F5F3",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Hanbok blue and red taeguk contrast, sleek modern K-pop edge.",
  },
  cyprus: {
    palette: {
      primary: "#1B6E5C",
      secondary: "#C8703A",
      accent: "#E8B93D",
      background: "#F6F3E9",
      surface: "#FFFFFF",
      text: "#1D1F1A",
    },
    shape: "organic",
    mood: "Mediterranean copper and turquoise, ancient stone warmth.",
  },
  croatia: {
    palette: {
      primary: "#B5202A",
      secondary: "#1E3A6B",
      accent: "#E8E4D8",
      background: "#F3F1EA",
      surface: "#FFFFFF",
      text: "#1B1B1B",
    },
    shape: "sharp",
    mood: "Adriatic red-and-blue checkerboard, walled-city stone.",
  },
  romania: {
    palette: {
      primary: "#1E3A6B",
      secondary: "#B5202A",
      accent: "#D4AF37",
      background: "#F4F1E9",
      surface: "#FFFFFF",
      text: "#1D1B18",
    },
    shape: "sharp",
    mood: "Carpathian castle gothic, medieval gold-on-navy heraldry.",
  },
  argentina: {
    palette: {
      primary: "#4E9CD9",
      secondary: "#1E1E1E",
      accent: "#E8B93D",
      background: "#F4F6F8",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Buenos Aires tango and Patagonian sky-blue, bold graphic energy.",
  },
  austria: {
    palette: {
      primary: "#B5202A",
      secondary: "#2E3B4E",
      accent: "#D4AF37",
      background: "#F5F3EC",
      surface: "#FFFFFF",
      text: "#1D1B18",
    },
    shape: "organic",
    mood: "Alpine red and imperial gold, Viennese waltz elegance.",
  },
  hungary: {
    palette: {
      primary: "#1E5B5A",
      secondary: "#9C6B30",
      accent: "#D4AF37",
      background: "#F6F0E4",
      surface: "#FFFFFF",
      text: "#20241F",
    },
    shape: "organic",
    mood: "Danube thermal-bath teal and gold, art-nouveau ornament.",
  },
  philippines: {
    palette: {
      primary: "#1E6E9C",
      secondary: "#D9A441",
      accent: "#C1443C",
      background: "#F5F6EE",
      surface: "#FFFFFF",
      text: "#1A1E1B",
    },
    shape: "rounded",
    mood: "Turquoise island lagoons, tropical sunset coral and gold.",
  },
};
