import type { ThemeConfig } from "./types";

/**
 * Starting theme direction per destination. As of the 2026-09-27 brand-color pass, `palette` is deliberately the
 * SAME purple/pink/lavender family (with per-destination variation, never a flat repeat) for every destination —
 * every screen and popup reads as our own brand rather than each destination's own unrelated color scheme, which
 * is what this table used to do. `shape` and `mood` still vary per destination for some real distinctiveness
 * without touching color. Typography is intentionally NOT part of this: one font (Rubik) is used site-wide (see
 * theme/fonts.ts) for consistency and readability.
 */
export const themePresets: Record<string, ThemeConfig> = {
  italy: {
    palette: {
      primary: "#7C3AED",
      secondary: "#C4B5FD",
      accent: "#EC4899",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#2B2420",
    },
    shape: "organic",
    mood: "Warm Mediterranean terracotta, olive, sun-bleached piazza stone.",
  },
  prague: {
    palette: {
      primary: "#8B5CF6",
      secondary: "#DDD6FE",
      accent: "#F472B6",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#231C1E",
    },
    shape: "sharp",
    mood: "Gothic spires, burgundy and gold, old-world engraved elegance.",
  },
  japan: {
    palette: {
      primary: "#6D28D9",
      secondary: "#A78BFA",
      accent: "#DB2777",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1F1F1F",
    },
    shape: "sharp",
    mood: "Wabi-sabi minimalism, sumi ink, single red accent like a hanko stamp.",
  },
  copenhagen: {
    palette: {
      primary: "#9F75E8",
      secondary: "#E9D5FF",
      accent: "#F0ABFC",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#25272B",
    },
    shape: "rounded",
    mood: "Hygge Scandinavian calm, dusty blue and warm wood tones.",
  },
  budapest: {
    palette: {
      primary: "#7E22CE",
      secondary: "#D8B4FE",
      accent: "#E879F9",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#20241F",
    },
    shape: "organic",
    mood: "Art nouveau thermal-bath elegance, teal and gold ornament.",
  },
  thailand: {
    palette: {
      primary: "#A78BFA",
      secondary: "#C4B5FD",
      accent: "#F9A8D4",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1D2D2C",
    },
    shape: "rounded",
    mood: "Tropical, saturated turquoise and coral, temple gold accents.",
  },
  china: {
    palette: {
      primary: "#6B46C1",
      secondary: "#B4A7F5",
      accent: "#EC4899",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Imperial red and gold, bold lacquer-and-ink graphic confidence.",
  },
  vietnam: {
    palette: {
      primary: "#9333EA",
      secondary: "#E9D5FF",
      accent: "#F472B6",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1E2420",
    },
    shape: "organic",
    mood: "Lush emerald rice terraces, saffron lantern light, riverside calm.",
  },
  poland: {
    palette: {
      primary: "#86198F",
      secondary: "#F0ABFC",
      accent: "#DB2777",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1F1E1D",
    },
    shape: "sharp",
    mood: "Amber and brick-red heritage, medieval square warmth.",
  },
  usa: {
    palette: {
      primary: "#7C2D92",
      secondary: "#E9D5FF",
      accent: "#F0ABFC",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Americana road-trip diner signage, navy and highway red.",
  },
  laos: {
    palette: {
      primary: "#5B21B6",
      secondary: "#C4B5FD",
      accent: "#E879F9",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#231E19",
    },
    shape: "organic",
    mood: "Mekong mist, saffron monk robes, quiet temple gold.",
  },
  cambodia: {
    palette: {
      primary: "#A855F7",
      secondary: "#F5D0FE",
      accent: "#F9A8D4",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#201C16",
    },
    shape: "organic",
    mood: "Sandstone temple carvings, jungle green, weathered Angkor gold.",
  },
  sweden: {
    palette: {
      primary: "#7C3AED",
      secondary: "#C4B5FD",
      accent: "#EC4899",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1E24",
    },
    shape: "rounded",
    mood: "Nordic blue and Falu-red cottages, clean minimal light.",
  },
  dubai: {
    palette: {
      primary: "#8B5CF6",
      secondary: "#DDD6FE",
      accent: "#F472B6",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#201C14",
    },
    shape: "sharp",
    mood: "Desert gold skyline, deep navy night, futuristic luxury.",
  },
  england: {
    palette: {
      primary: "#6D28D9",
      secondary: "#A78BFA",
      accent: "#DB2777",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1B1B1B",
    },
    shape: "sharp",
    mood: "Rainy London brick, red telephone box, old-world crest gold.",
  },
  netherlands: {
    palette: {
      primary: "#9F75E8",
      secondary: "#E9D5FF",
      accent: "#F0ABFC",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1E1D1A",
    },
    shape: "rounded",
    mood: "Tulip orange and canal-house blue, tidy graphic clarity.",
  },
  tanzania: {
    palette: {
      primary: "#7E22CE",
      secondary: "#D8B4FE",
      accent: "#E879F9",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#231C15",
    },
    shape: "organic",
    mood: "Savanna dust and acacia gold, Zanzibar turquoise coastline.",
  },
  greece: {
    palette: {
      primary: "#A78BFA",
      secondary: "#C4B5FD",
      accent: "#F9A8D4",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1E22",
    },
    shape: "rounded",
    mood: "Whitewashed Cycladic walls, Aegean blue, sun-bleached stone.",
  },
  norway: {
    palette: {
      primary: "#6B46C1",
      secondary: "#B4A7F5",
      accent: "#EC4899",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1E24",
    },
    shape: "sharp",
    mood: "Fjord slate blue, aurora-green accent, crisp Nordic minimalism.",
  },
  singapore: {
    palette: {
      primary: "#9333EA",
      secondary: "#E9D5FF",
      accent: "#F472B6",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Garden-city green and Marina Bay skyline red, modern sheen.",
  },
  spain: {
    palette: {
      primary: "#86198F",
      secondary: "#F0ABFC",
      accent: "#DB2777",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#221C15",
    },
    shape: "organic",
    mood: "Flamenco red and gold, sun-drenched plaza warmth.",
  },
  portugal: {
    palette: {
      primary: "#7C2D92",
      secondary: "#E9D5FF",
      accent: "#F0ABFC",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1B1E1D",
    },
    shape: "rounded",
    mood: "Azulejo tile blue, terracotta rooftops, coastal light.",
  },
  france: {
    palette: {
      primary: "#5B21B6",
      secondary: "#C4B5FD",
      accent: "#E879F9",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1D1B18",
    },
    shape: "sharp",
    mood: "Parisian navy and bordeaux, gilded café elegance.",
  },
  korea: {
    palette: {
      primary: "#A855F7",
      secondary: "#F5D0FE",
      accent: "#F9A8D4",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Hanbok blue and red taeguk contrast, sleek modern K-pop edge.",
  },
  cyprus: {
    palette: {
      primary: "#7C3AED",
      secondary: "#C4B5FD",
      accent: "#EC4899",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1D1F1A",
    },
    shape: "organic",
    mood: "Mediterranean copper and turquoise, ancient stone warmth.",
  },
  croatia: {
    palette: {
      primary: "#8B5CF6",
      secondary: "#DDD6FE",
      accent: "#F472B6",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1B1B1B",
    },
    shape: "sharp",
    mood: "Adriatic red-and-blue checkerboard, walled-city stone.",
  },
  romania: {
    palette: {
      primary: "#6D28D9",
      secondary: "#A78BFA",
      accent: "#DB2777",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1D1B18",
    },
    shape: "sharp",
    mood: "Carpathian castle gothic, medieval gold-on-navy heraldry.",
  },
  argentina: {
    palette: {
      primary: "#9F75E8",
      secondary: "#E9D5FF",
      accent: "#F0ABFC",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1A1A",
    },
    shape: "sharp",
    mood: "Buenos Aires tango and Patagonian sky-blue, bold graphic energy.",
  },
  austria: {
    palette: {
      primary: "#7E22CE",
      secondary: "#D8B4FE",
      accent: "#E879F9",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1D1B18",
    },
    shape: "organic",
    mood: "Alpine red and imperial gold, Viennese waltz elegance.",
  },
  hungary: {
    palette: {
      primary: "#A78BFA",
      secondary: "#C4B5FD",
      accent: "#F9A8D4",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#20241F",
    },
    shape: "organic",
    mood: "Danube thermal-bath teal and gold, art-nouveau ornament.",
  },
  philippines: {
    palette: {
      primary: "#6B46C1",
      secondary: "#B4A7F5",
      accent: "#EC4899",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1E1B",
    },
    shape: "rounded",
    mood: "Turquoise island lagoons, tropical sunset coral and gold.",
  },
  estonia: {
    palette: {
      primary: "#9333EA",
      secondary: "#E9D5FF",
      accent: "#F472B6",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1E2328",
    },
    shape: "sharp",
    mood: "Medieval Baltic blue and terracotta rooftops, Hanseatic old-town charm.",
  },
  latvia: {
    palette: {
      primary: "#86198F",
      secondary: "#F0ABFC",
      accent: "#DB2777",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#231C1A",
    },
    shape: "organic",
    mood: "Riga art-nouveau brick and gold, ornate Jugendstil facades.",
  },
  lithuania: {
    palette: {
      primary: "#7C2D92",
      secondary: "#E9D5FF",
      accent: "#F0ABFC",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#231D18",
    },
    shape: "organic",
    mood: "Vilnius baroque terracotta and Baltic amber warmth.",
  },
  malta: {
    palette: {
      primary: "#5B21B6",
      secondary: "#C4B5FD",
      accent: "#E879F9",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#231F1A",
    },
    shape: "rounded",
    mood: "Golden limestone bastions against deep Mediterranean blue.",
  },
  switzerland: {
    palette: {
      primary: "#A855F7",
      secondary: "#F5D0FE",
      accent: "#F9A8D4",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1B1E1D",
    },
    shape: "sharp",
    mood: "Crisp alpine red and glacier blue, precise mountain clarity.",
  },
  hongkong: {
    palette: {
      primary: "#7C3AED",
      secondary: "#C4B5FD",
      accent: "#EC4899",
      background: "#FBF9FF",
      surface: "#FFFFFF",
      text: "#1A1A1E",
    },
    shape: "sharp",
    mood: "Neon skyline energy meets Macau's colonial pastel calm.",
  },
};
